FROM node:10.5

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

COPY package.json .

#COPY package-lock.json .

RUN npm install

RUN npm install -g @angular/cli@1.7.1

COPY package-lock.json .

COPY . /usr/src/app

EXPOSE 4200

CMD ng serve --host 0.0.0.0 --disableHostCheck